def get_config() -> dict:
    return {
        0: "DE_SHARP_S",
        1: "DE_0",
        2: "DE_9",
        3: "DE_8",
        4: "DE_7",
        5: "DE_6",
        6: "RCTRL",
        7: "DE_UE",
        8: "DE_P",
        9: "DE_O",
        10: "DE_I",
        11: "DE_U",
        12: "DE_Z",
        13: "RALT",
        14: "DE_AE",
        15: "DE_OE",
        16: "DE_L",
        17: "DE_K",
        18: "DE_J",
        19: "DE_H",
        20: "RMETA",
        21: "RSHIFT",
        22: "DE_MINUS",
        23: "DE_DOT",
        24: "DE_COMMA",
        25: "DE_M",
        26: "DE_N",
        27: "PASSWORD_MANAGER_ENABLE",
        28: "DE_RIGHT",
        29: "DE_DOWN",
        30: "DE_UP",
        31: "DE_LEFT",
        32: "ALTGR",
        33: "SPACE",
        34: "ENTER",
        35: "ESC",
        36: "DE_1",
        37: "DE_2",
        38: "DE_3",
        39: "DE_4",
        40: "DE_5",
        41: "LCTRL",
        42: "TAB",
        43: "DE_Q",
        44: "DE_W",
        45: "DE_E",
        46: "DE_R",
        47: "DE_T",
        48: "LALT",
        49: "CAPS",
        50: "DE_A",
        51: "DE_S",
        52: "DE_D",
        53: "DE_F",
        54: "DE_G",
        55: "WINDOWS",
        56: "LSHIFT",
        57: "DE_Y",
        58: "DE_X",
        59: "DE_C",
        60: "DE_V",
        61: "DE_B",
        62: "PASSWORD_MANAGER_ENABLE",
        63: "DE_SMALLER",
        64: "DE_PLUS",
        65: "DE_RAUTE",
        66: NotImplementedError,
        67: "ALTGR",
        68: "BACKSPACE",
        69: "DEL"
    }


def get_qwertz_layer_1() -> dict:
    return {"DE_0": "0",
            "DE_1": "1",
            "DE_2": "2",
            "DE_3": "3",
            "DE_4": "4",
            "DE_5": "5",
            "DE_6": "6",
            "DE_7": "7",
            "DE_8": "8",
            "DE_9": "9",
            "DE_A": "a",
            "DE_B": "b",
            "DE_C": "c",
            "DE_D": "d",
            "DE_E": "e",
            "DE_F": "f",
            "DE_G": "g",
            "DE_H": "h",
            "DE_I": "i",
            "DE_J": "j",
            "DE_K": "k",
            "DE_L": "l",
            "DE_M": "m",
            "DE_N": "n",
            "DE_O": "o",
            "DE_P": "p",
            "DE_Q": "q",
            "DE_R": "r",
            "DE_S": "s",
            "DE_T": "t",
            "DE_U": "u",
            "DE_V": "v",
            "DE_W": "w",
            "DE_X": "x",
            "DE_Y": "z",
            "DE_Z": "y",
            "DE_OE": "ö",
            "DE_AE": "ä",
            "DE_UE": "ü",
            "DE_SHARP_S": "ß",
            "DE_MINUS": "-",
            "DE_DOT": ".",
            "DE_COMMA": ",",
            "ENTER": "\n",
            "DE_UP": chr(17),
            "DE_DOWN": chr(18),
            "DE_RIGHT": chr(19),
            "DE_LEFT": chr(20),
            "BACKSPACE": "\b",
            "SPACE": " ",
            "DE_SMALLER": "<",
            "DE_PLUS": "+",
            "DE_RAUTE": "#"
            }


def get_qwertz_layer_2() -> dict:
    return {"DE_0": "=",
            "DE_1": "!",
            "DE_2": "\"",
            "DE_3": "§",
            "DE_4": "$",
            "DE_5": "%",
            "DE_6": "&",
            "DE_7": "/",
            "DE_8": "(",
            "DE_9": ")",
            "DE_A": "A",
            "DE_B": "B",
            "DE_C": "C",
            "DE_D": "D",
            "DE_E": "E",
            "DE_F": "F",
            "DE_G": "G",
            "DE_H": "H",
            "DE_I": "I",
            "DE_J": "J",
            "DE_K": "K",
            "DE_L": "L",
            "DE_M": "M",
            "DE_N": "N",
            "DE_O": "O",
            "DE_P": "P",
            "DE_Q": "Q",
            "DE_R": "R",
            "DE_S": "S",
            "DE_T": "T",
            "DE_U": "U",
            "DE_V": "V",
            "DE_W": "W",
            "DE_X": "X",
            "DE_Y": "Z",
            "DE_Z": "Y",
            "DE_OE": "Ö",
            "DE_AE": "Ä",
            "DE_UE": "Ü",
            "DE_SHARP_S": "?",
            "DE_MINUS": "_",
            "DE_DOT": ":",
            "DE_COMMA": ";",
            "ENTER": "\n",
            "DE_SMALLER": ">",
            "DE_PLUS": "*",
            "DE_RAUTE": "'"
            }


def get_qwertz_layer_3() -> dict:
    return {}


def get_modifier_usb_keycodes() -> dict:
    return {"LCTRL": 0x01,
            "LSHIFT": 0x02,
            "LALT": 0x04,
            "LMETA": 0x08,
            "RCTRL": 0x10,
            "RSHIFT": 0x20,
            "RALT": 0x40,
            "RMETA": 0x80
            # todo add altgr
            }


def get_usb_keycodes() -> dict:
    return {None: 0x00,
            "DE_A": 0x04,
            "DE_B": 0x05,
            "DE_C": 0x06,
            "DE_D": 0x07,
            "DE_E": 0x08,
            "DE_F": 0x09,
            "DE_G": 0x0a,
            "DE_H": 0x0b,
            "DE_I": 0x0c,
            "DE_J": 0x0d,
            "DE_K": 0x0e,
            "DE_L": 0x0f,
            "DE_M": 0x10,
            "DE_N": 0x11,
            "DE_O": 0x12,
            "DE_P": 0x13,
            "DE_Q": 0x14,
            "DE_R": 0x15,
            "DE_S": 0x16,
            "DE_T": 0x17,
            "DE_U": 0x18,
            "DE_V": 0x19,
            "DE_W": 0x1a,
            "DE_X": 0x1b,
            "DE_Y": 0x1c,
            "DE_Z": 0x1d,
            "DE_1": 0x1e,
            "DE_2": 0x1f,
            "DE_3": 0x20,
            "DE_4": 0x21,
            "DE_5": 0x22,
            "DE_6": 0x23,
            "DE_7": 0x24,
            "DE_8": 0x25,
            "DE_9": 0x26,
            "DE_0": 0x27,
            "ENTER": 0x28,
            "ESC": 0x29,
            "BACKSPACE": 0x2a,
            "TAB": 0x2b,
            "SPACE": 0x2c,
            "DE_SHARP_S": 0x2d,
            "DE_UE": 0x2f,
            "DE_PLUS": 0x30,
            "DE_OE": 0x33,
            "DE_AE": 0x34,
            "DE_RAUTE": 0x32,
            "DE_SMALLER": 0x64,
            "DE_COMMA": 0x36,
            "DE_DOT": 0x37,
            "DE_MINUS": 0x38
            }


def get_keycodes_from_char() -> dict:
    return {"a": ["DE_A"],
            "A": ["DE_A", "LSHIFT"],
            "b": ["DE_B"],
            "B": ["DE_B", "LSHIFT"],
            "c": ["DE_C"],
            "C": ["DE_C", "LSHIFT"],
            "d": ["DE_D"],
            "D": ["DE_D", "LSHIFT"],
            "e": ["DE_E"],
            "E": ["DE_E", "LSHIFT"],
            "€": ["DE_E", "ALTGR"],
            "f": ["DE_F"],
            "F": ["DE_F", "LSHIFT"],
            "g": ["DE_G"],
            "G": ["DE_G", "LSHIFT"],
            "h": ["DE_H"],
            "H": ["DE_H", "LSHIFT"],
            "i": ["DE_I"],
            "I": ["DE_I", "LSHIFT"],
            "j": ["DE_J"],
            "J": ["DE_J", "LSHIFT"],
            "k": ["DE_K"],
            "K": ["DE_K", "LSHIFT"],
            "l": ["DE_L"],
            "L": ["DE_L", "LSHIFT"],
            "m": ["DE_M"],
            "M": ["DE_M", "LSHIFT"],
            "n": ["DE_N"],
            "N": ["DE_N", "LSHIFT"],
            "o": ["DE_O"],
            "O": ["DE_O", "LSHIFT"],
            "p": ["DE_P"],
            "P": ["DE_P", "LSHIFT"],
            "q": ["DE_Q"],
            "Q": ["DE_Q", "LSHIFT"],
            "r": ["DE_R"],
            "R": ["DE_R", "LSHIFT"],
            "s": ["DE_S"],
            "S": ["DE_S", "LSHIFT"],
            "t": ["DE_T"],
            "T": ["DE_T", "LSHIFT"],
            "u": ["DE_U"],
            "U": ["DE_U", "LSHIFT"],
            "v": ["DE_V"],
            "V": ["DE_V", "LSHIFT"],
            "w": ["DE_W"],
            "W": ["DE_W", "LSHIFT"],
            "x": ["DE_X"],
            "X": ["DE_X", "LSHIFT"],
            "y": ["DE_Y"],
            "Y": ["DE_Y", "LSHIFT"],
            "z": ["DE_Z"],
            "Z": ["DE_Z", "LSHIFT"],
            "ü": ["DE_UE"],
            "Ü": ["DE_UE", "LSHIFT"],
            "ö": ["DE_OE"],
            "Ö": ["DE_OE", "LSHIFT"],
            "ä": ["DE_AE"],
            "Ä": ["DE_AE", "LSHIFT"],
            "0": ["DE_0"],
            "1": ["DE_1"],
            "2": ["DE_2"],
            "3": ["DE_3"],
            "4": ["DE_4"],
            "5": ["DE_5"],
            "6": ["DE_6"],
            "7": ["DE_7"],
            "8": ["DE_8"],
            "9": ["DE_9"],
            "ß": ["DE_SHARP_S"],
            "!": ["DE_1", "LSHIFT"],
            "\"": ["DE_2", "LSHIFT"],
            "§": ["DE_3", "LSHIFT"],
            "$": ["DE_4", "LSHIFT"],
            "%": ["DE_5", "LSHIFT"],
            "&": ["DE_6", "LSHIFT"],
            "/": ["DE_7", "LSHIFT"],
            "(": ["DE_8", "LSHIFT"],
            ")": ["DE_9", "LSHIFT"],
            "=": ["DE_0", "LSHIFT"],
            "?": ["DE_SHARP_S", "LSHIFT"],
            "+": ["DE_PLUS"],
            "*": ["DE_PLUS", "LSHIFT"],
            "~": ["DE_PLUS", "ALTGR"],
            "#": ["DE_RAUTE"],
            "'": ["DE_RAUTE", "LSHIFT"],
            "’": ["DE_RAUTE", "ALTGR"],
            ",": ["DE_COMMA"],
            ";": ["DE_COMMA", "LSHIFT"],
            "·": ["DE_COMMA", "ALTGR"],
            ".": ["DE_DOT"],
            ":": ["DE_DOT", "LSHIFT"],
            "…": ["DE_DOT", "LSHIFT"],
            "-": ["DE_MINUS"],
            "_": ["DE_MINUS", "LSHIFT"],
            "–": ["DE_MINUS", "ALTGR"],
            "<": ["DE_SMALLER"],
            ">": ["DE_SMALLER", "LSHIFT"],
            "|": ["DE_SMALLER", "ALTGR"]
            }
